//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class EquipmentHmiData
    {
        public int EquipmentID { get; set; }
        public string Tags { get; set; }
        public string Screens { get; set; }
        public string Alarms { get; set; }
    
        public virtual Equipment1 Equipment { get; set; }
    }
    
}
