//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class ErrorLog
    {
        public int ErrorLogID { get; set; }
        public Nullable<System.DateTime> ErrorTime { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ErrorNumber { get; set; }
        public Nullable<int> ErrorSeverity { get; set; }
        public string ErrorState { get; set; }
        public string ErrorProcedure { get; set; }
        public Nullable<int> ErrorLine { get; set; }
        public string ErrorMessage { get; set; }
    }
    
}
