//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class Inerliner : Material
    {
        public Nullable<int> Width { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<decimal> Thickness { get; set; }
        public Nullable<int> Weight { get; set; }
    }
    
}
