//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class Lank : Material
    {
        public string LankTT { get; set; }
        public Nullable<int> Perimeter { get; set; }
        public Nullable<int> Diameter { get; set; }
    }
    
}
