//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class ParametarRequirement
    {
        public int ResourceParametarID { get; set; }
        public Nullable<int> ParentResourceParametarID { get; set; }
        public int WorkRequestID { get; set; }
        public string Value { get; set; }
        public string UnitOfMeasure { get; set; }
    }
    
}
