//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class Ply : Material
    {
        public Nullable<int> Width { get; set; }
        public Nullable<int> Lenght { get; set; }
        public Nullable<decimal> Angle { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<byte> Number { get; set; }
        public string Symbol { get; set; }
    }
    
}
