//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class Reason
    {
        public Reason()
        {
            this.ResourceCapabilities = new HashSet<ResourceCapability>();
        }
    
        public int ReasonID { get; set; }
        public Nullable<int> ParentResonID { get; set; }
        public Nullable<int> Level { get; set; }
        public string Symbol { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Calculate { get; set; }
        public Nullable<int> ReferencialID { get; set; }
    
        public virtual ICollection<ResourceCapability> ResourceCapabilities { get; set; }
    }
    
}
