//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class ResourceLot
    {
        public ResourceLot()
        {
            this.ResourceActuals = new HashSet<ResourceActual>();
            this.ResourceCapabilities = new HashSet<ResourceCapability>();
            this.ResourceLotTrackings = new HashSet<ResourceLotTracking>();
            this.ResourceProperties = new HashSet<ResourceProperty>();
            this.ResourceRequirements = new HashSet<ResourceRequirement>();
            this.ResourceSpecifications = new HashSet<ResourceSpecification>();
        }
    
        public int ResourceLotID { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public Nullable<int> ResourceDefinitionID { get; set; }
        public Nullable<int> ResourceLotStatusID { get; set; }
        public Nullable<float> Quantity { get; set; }
        public string QuantityUnitOfMeasure { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastChangeDate { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<int> LocationID { get; set; }
    
        public virtual ICollection<ResourceActual> ResourceActuals { get; set; }
        public virtual ICollection<ResourceCapability> ResourceCapabilities { get; set; }
        public virtual ResourceDefinition ResourceDefinition { get; set; }
        public virtual ResourceLotStatus ResourceLotStatu { get; set; }
        public virtual ICollection<ResourceLotTracking> ResourceLotTrackings { get; set; }
        public virtual ICollection<ResourceProperty> ResourceProperties { get; set; }
        public virtual ICollection<ResourceRequirement> ResourceRequirements { get; set; }
        public virtual ICollection<ResourceSpecification> ResourceSpecifications { get; set; }
    }
    
}
