//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class ResourceClass
    {
        public ResourceClass()
        {
            this.ResourceDefinitions = new HashSet<ResourceDefinition>();
            this.ResourceProperties = new HashSet<ResourceProperty>();
            this.ResourceRequirements = new HashSet<ResourceRequirement>();
            this.ResourceSpecifications = new HashSet<ResourceSpecification>();
        }
    
        public int ResourceClassID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ResourceType { get; set; }
        public Nullable<int> ResourceLevelID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> ParentClassID { get; set; }
    
        public virtual ICollection<ResourceDefinition> ResourceDefinitions { get; set; }
        public virtual ICollection<ResourceProperty> ResourceProperties { get; set; }
        public virtual ICollection<ResourceRequirement> ResourceRequirements { get; set; }
        public virtual ICollection<ResourceSpecification> ResourceSpecifications { get; set; }
        public virtual ResourceClass ParentClass { get; set; }
    }
    
}
