//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class ResourceRequirement
    {
        public ResourceRequirement()
        {
            this.ResourceRequirementProperties = new HashSet<ResourceRequirementProperty>();
        }
    
        public int ResourceRequirementID { get; set; }
        public Nullable<int> ResourceID { get; set; }
        public Nullable<int> ResourceTypeID { get; set; }
        public Nullable<int> WorkRequestID { get; set; }
        public Nullable<int> ResourceUse { get; set; }
        public string Description { get; set; }
        public Nullable<float> Quantity { get; set; }
        public string QuantityUnitOfMeasure { get; set; }
    
        public virtual ResourceClass ResourceClass { get; set; }
        public virtual ResourceDefinition ResourceDefinition { get; set; }
        public virtual ResourceLot ResourceLot { get; set; }
        public virtual ResourceType ResourceType { get; set; }
        public virtual ICollection<ResourceRequirementProperty> ResourceRequirementProperties { get; set; }
    }
    
}
