//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public abstract partial class ResourceDefinition
    {
        public ResourceDefinition()
        {
            this.ResourceActuals = new HashSet<ResourceActual>();
            this.ResourceCapabilities = new HashSet<ResourceCapability>();
            this.ResourceLots = new HashSet<ResourceLot>();
            this.ResourceProperties = new HashSet<ResourceProperty>();
            this.ResourceRequirements = new HashSet<ResourceRequirement>();
            this.ResourceSpecifications = new HashSet<ResourceSpecification>();
            this.ResourcePhotos = new HashSet<ResourcePhoto>();
        }
    
        public int ResourceDefinitionID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ResourceClassID { get; set; }
        public Nullable<int> ParentResourceDefinitionID { get; set; }
    
        public virtual ResourceClass ResourceClass { get; set; }
        public virtual ICollection<ResourceActual> ResourceActuals { get; set; }
        public virtual ICollection<ResourceCapability> ResourceCapabilities { get; set; }
        public virtual ICollection<ResourceLot> ResourceLots { get; set; }
        public virtual ICollection<ResourceProperty> ResourceProperties { get; set; }
        public virtual ICollection<ResourceRequirement> ResourceRequirements { get; set; }
        public virtual ICollection<ResourceSpecification> ResourceSpecifications { get; set; }
        public virtual ICollection<ResourcePhoto> ResourcePhotos { get; set; }
    }
    
}
