//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class ResourceProperty
    {
        public int PropertyID { get; set; }
        public int ResourceID { get; set; }
        public string ResourceType { get; set; }
        public string NominalValue { get; set; }
        public string DataType { get; set; }
        public string UnitOfMeasure { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual ResourceClass ResourceClass { get; set; }
        public virtual ResourceDefinition ResourceDefinition { get; set; }
        public virtual ResourceLot ResourceLot { get; set; }
    }
    
}
