//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class ResourceType
    {
        public ResourceType()
        {
            this.ResourceActuals = new HashSet<ResourceActual>();
            this.ResourceRequirements = new HashSet<ResourceRequirement>();
            this.ResourceSpecifications = new HashSet<ResourceSpecification>();
        }
    
        public int ResourceTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ResourceActual> ResourceActuals { get; set; }
        public virtual ICollection<ResourceRequirement> ResourceRequirements { get; set; }
        public virtual ICollection<ResourceSpecification> ResourceSpecifications { get; set; }
    }
    
}
