//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class ResourceInventory
    {
        public int ResourceInventoryID { get; set; }
        public Nullable<int> ResourceDefinitionID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string UnitOfMeasure { get; set; }
    }
    
}
