//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class ResourceCapability
    {
        public ResourceCapability()
        {
            this.ResourceCapabilityProperties = new HashSet<ResourceCapabilityProperty>();
        }
    
        public int ResourceCapabilityID { get; set; }
        public Nullable<int> WorkCapabilityID { get; set; }
        public Nullable<int> WorkProcessSegmentID { get; set; }
        public Nullable<int> ResourceID { get; set; }
        public string ResourceUseID { get; set; }
        public Nullable<int> ResourceType { get; set; }
        public string Description { get; set; }
        public Nullable<int> CapabilityTypeID { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public Nullable<float> ConfidenceFactor { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Quantity { get; set; }
        public string QuantityUnitOfMeasure { get; set; }
        public Nullable<int> AssemblyTypeID { get; set; }
        public Nullable<int> ParentResourceAssemblyID { get; set; }
        public string HierarchyScope { get; set; }
    
        public virtual Reason Reason { get; set; }
        public virtual ResourceDefinition ResourceDefinition { get; set; }
        public virtual ResourceLot ResourceLot { get; set; }
        public virtual WorkCapability WorkCapability { get; set; }
        public virtual WorkProcessSegment WorkProcessSegment { get; set; }
        public virtual ICollection<ResourceCapabilityProperty> ResourceCapabilityProperties { get; set; }
    }
    
}
