//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class ResourceActualProperty
    {
        public int ResourceActualID { get; set; }
        public int PropertyID { get; set; }
        public string Description { get; set; }
        public Nullable<float> Value { get; set; }
        public string ValueUnitOfMeasure { get; set; }
        public Nullable<float> Quantity { get; set; }
        public string QuantityUnitOfMeasure { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual ResourceActual ResourceActual { get; set; }
    }
    
}
