//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class ResourceLotStatus
    {
        public ResourceLotStatus()
        {
            this.ResourceLots = new HashSet<ResourceLot>();
        }
    
        public int ResourceLotStatusID { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ResourceLot> ResourceLots { get; set; }
    }
    
}
