//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class ResourceLotTracking
    {
        public int ResourceLotTrackingID { get; set; }
        public Nullable<int> ResourceLotID { get; set; }
        public string Operation { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> TrackingDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
    
        public virtual ResourceLot ResourceLot { get; set; }
    }
    
}
