//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class ScooterRawTyre : Material
    {
        public string CAI { get; set; }
        public string InternalCodeText { get; set; }
        public Nullable<int> InternalCode { get; set; }
        public string Dimension { get; set; }
        public Nullable<bool> Active { get; set; }
    }
    
}
