//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class Sequence
    {
        public string SequenceID { get; set; }
        public string Description { get; set; }
        public Nullable<int> CurrentValue { get; set; }
        public Nullable<int> MinValue { get; set; }
        public Nullable<int> MaxValue { get; set; }
        public string SequencePrefix { get; set; }
        public string SequenceSuffix { get; set; }
        public Nullable<System.DateTime> LastChange { get; set; }
        public Nullable<int> LastUserID { get; set; }
    }
    
}
