//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class TestResult
    {
        public int TestResultID { get; set; }
        public Nullable<int> TestSpecificationID { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
        public Nullable<int> UserID { get; set; }
    }
    
}
