//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class TestResultProperty
    {
        public int PropertyID { get; set; }
        public int TestResultID { get; set; }
        public string Value { get; set; }
        public string DataType { get; set; }
        public string UnitOfMeasure { get; set; }
    }
    
}
