//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class WorkSchedule
    {
        public int WorkScheduleID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> WorkTypeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public string HierarchyScope { get; set; }
        public Nullable<int> ParentWorkScheduleID { get; set; }
    }
    
}
