//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class WorkResponse
    {
        public WorkResponse()
        {
            this.ResourceActuals = new HashSet<ResourceActual>();
        }
    
        public int WorkResponseID { get; set; }
        public Nullable<int> WorkTypeID { get; set; }
        public Nullable<int> WorkRequestID { get; set; }
        public Nullable<int> WorkDefinitionID { get; set; }
        public Nullable<int> ParentWorkResponseID { get; set; }
        public Nullable<int> WorkPerformanceID { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string EndTime { get; set; }
        public string HierarchyScope { get; set; }
        public Nullable<System.TimeSpan> Downtime { get; set; }
        public Nullable<System.TimeSpan> ProductionTime { get; set; }
        public string UndefinedTime { get; set; }
        public Nullable<int> NumberOfGood { get; set; }
        public Nullable<int> NumberOfBad { get; set; }
        public Nullable<int> NumberOfLost { get; set; }
    
        public virtual ICollection<ResourceActual> ResourceActuals { get; set; }
    }
    
}
