//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class WorkCapability
    {
        public WorkCapability()
        {
            this.ResourceCapabilities = new HashSet<ResourceCapability>();
        }
    
        public int WorkCapabilityID { get; set; }
        public Nullable<int> WorkProcessSegementID { get; set; }
    
        public virtual ICollection<ResourceCapability> ResourceCapabilities { get; set; }
    }
    
}
