//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace T2T.Model
{
    public partial class WorkRequest
    {
        public int WorkRequestID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> WorkType { get; set; }
        public Nullable<int> WorkDefinitionID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Priority { get; set; }
        public string HierarchyScope { get; set; }
        public Nullable<int> ParentWorkRequestID { get; set; }
    }
    
}
