//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SpecModel", "FK_Spec_CAI", "CAI", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(T2T.Web.Models.CAI), "Spec", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(T2T.Web.Models.Spec), true)]

#endregion

namespace T2T.Web.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TREntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TREntities2 object using the connection string found in the 'TREntities2' section of the application configuration file.
        /// </summary>
        public TREntities2() : base("name=TREntities2", "TREntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TREntities2 object.
        /// </summary>
        public TREntities2(string connectionString) : base(connectionString, "TREntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TREntities2 object.
        /// </summary>
        public TREntities2(EntityConnection connection) : base(connection, "TREntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CAI> CAIs
        {
            get
            {
                if ((_CAIs == null))
                {
                    _CAIs = base.CreateObjectSet<CAI>("CAIs");
                }
                return _CAIs;
            }
        }
        private ObjectSet<CAI> _CAIs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Spec> Specs
        {
            get
            {
                if ((_Specs == null))
                {
                    _Specs = base.CreateObjectSet<Spec>("Specs");
                }
                return _Specs;
            }
        }
        private ObjectSet<Spec> _Specs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CAIs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCAIs(CAI cAI)
        {
            base.AddObject("CAIs", cAI);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Specs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSpecs(Spec spec)
        {
            base.AddObject("Specs", spec);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SpecModel", Name="CAI")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CAI : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CAI object.
        /// </summary>
        /// <param name="cAI1">Initial value of the CAI1 property.</param>
        /// <param name="interniKod">Initial value of the InterniKod property.</param>
        public static CAI CreateCAI(global::System.String cAI1, global::System.String interniKod)
        {
            CAI cAI = new CAI();
            cAI.CAI1 = cAI1;
            cAI.InterniKod = interniKod;
            return cAI;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CAI1
        {
            get
            {
                return _CAI1;
            }
            set
            {
                if (_CAI1 != value)
                {
                    OnCAI1Changing(value);
                    ReportPropertyChanging("CAI1");
                    _CAI1 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CAI1");
                    OnCAI1Changed();
                }
            }
        }
        private global::System.String _CAI1;
        partial void OnCAI1Changing(global::System.String value);
        partial void OnCAI1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BarKodFamilija
        {
            get
            {
                return _BarKodFamilija;
            }
            set
            {
                OnBarKodFamilijaChanging(value);
                ReportPropertyChanging("BarKodFamilija");
                _BarKodFamilija = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BarKodFamilija");
                OnBarKodFamilijaChanged();
            }
        }
        private global::System.String _BarKodFamilija;
        partial void OnBarKodFamilijaChanging(global::System.String value);
        partial void OnBarKodFamilijaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InterniKod
        {
            get
            {
                return _InterniKod;
            }
            set
            {
                OnInterniKodChanging(value);
                ReportPropertyChanging("InterniKod");
                _InterniKod = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("InterniKod");
                OnInterniKodChanged();
            }
        }
        private global::System.String _InterniKod;
        partial void OnInterniKodChanging(global::System.String value);
        partial void OnInterniKodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Naziv
        {
            get
            {
                return _Naziv;
            }
            set
            {
                OnNazivChanging(value);
                ReportPropertyChanging("Naziv");
                _Naziv = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Naziv");
                OnNazivChanged();
            }
        }
        private global::System.String _Naziv;
        partial void OnNazivChanging(global::System.String value);
        partial void OnNazivChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dezen
        {
            get
            {
                return _Dezen;
            }
            set
            {
                OnDezenChanging(value);
                ReportPropertyChanging("Dezen");
                _Dezen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dezen");
                OnDezenChanged();
            }
        }
        private global::System.String _Dezen;
        partial void OnDezenChanging(global::System.String value);
        partial void OnDezenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dimenzija
        {
            get
            {
                return _Dimenzija;
            }
            set
            {
                OnDimenzijaChanging(value);
                ReportPropertyChanging("Dimenzija");
                _Dimenzija = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dimenzija");
                OnDimenzijaChanged();
            }
        }
        private global::System.String _Dimenzija;
        partial void OnDimenzijaChanging(global::System.String value);
        partial void OnDimenzijaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Aktivan
        {
            get
            {
                return _Aktivan;
            }
            set
            {
                OnAktivanChanging(value);
                ReportPropertyChanging("Aktivan");
                _Aktivan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Aktivan");
                OnAktivanChanged();
            }
        }
        private Nullable<global::System.Boolean> _Aktivan;
        partial void OnAktivanChanging(Nullable<global::System.Boolean> value);
        partial void OnAktivanChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SpecModel", "FK_Spec_CAI", "Spec")]
        public EntityCollection<Spec> Specs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Spec>("SpecModel.FK_Spec_CAI", "Spec");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Spec>("SpecModel.FK_Spec_CAI", "Spec", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SpecModel", Name="Spec")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Spec : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Spec object.
        /// </summary>
        /// <param name="cB">Initial value of the CB property.</param>
        public static Spec CreateSpec(global::System.String cB)
        {
            Spec spec = new Spec();
            spec.CB = cB;
            return spec;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StatusDimenzije
        {
            get
            {
                return _StatusDimenzije;
            }
            set
            {
                OnStatusDimenzijeChanging(value);
                ReportPropertyChanging("StatusDimenzije");
                _StatusDimenzije = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StatusDimenzije");
                OnStatusDimenzijeChanged();
            }
        }
        private global::System.String _StatusDimenzije;
        partial void OnStatusDimenzijeChanging(global::System.String value);
        partial void OnStatusDimenzijeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CAI
        {
            get
            {
                return _CAI;
            }
            set
            {
                OnCAIChanging(value);
                ReportPropertyChanging("CAI");
                _CAI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CAI");
                OnCAIChanged();
            }
        }
        private global::System.String _CAI;
        partial void OnCAIChanging(global::System.String value);
        partial void OnCAIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CB
        {
            get
            {
                return _CB;
            }
            set
            {
                if (_CB != value)
                {
                    OnCBChanging(value);
                    ReportPropertyChanging("CB");
                    _CB = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CB");
                    OnCBChanged();
                }
            }
        }
        private global::System.String _CB;
        partial void OnCBChanging(global::System.String value);
        partial void OnCBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PDI
        {
            get
            {
                return _PDI;
            }
            set
            {
                OnPDIChanging(value);
                ReportPropertyChanging("PDI");
                _PDI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PDI");
                OnPDIChanged();
            }
        }
        private global::System.String _PDI;
        partial void OnPDIChanging(global::System.String value);
        partial void OnPDIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DatumPDI
        {
            get
            {
                return _DatumPDI;
            }
            set
            {
                OnDatumPDIChanging(value);
                ReportPropertyChanging("DatumPDI");
                _DatumPDI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DatumPDI");
                OnDatumPDIChanged();
            }
        }
        private Nullable<global::System.DateTime> _DatumPDI;
        partial void OnDatumPDIChanging(Nullable<global::System.DateTime> value);
        partial void OnDatumPDIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TestBroj
        {
            get
            {
                return _TestBroj;
            }
            set
            {
                OnTestBrojChanging(value);
                ReportPropertyChanging("TestBroj");
                _TestBroj = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TestBroj");
                OnTestBrojChanged();
            }
        }
        private global::System.String _TestBroj;
        partial void OnTestBrojChanging(global::System.String value);
        partial void OnTestBrojChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MasaGume
        {
            get
            {
                return _MasaGume;
            }
            set
            {
                OnMasaGumeChanging(value);
                ReportPropertyChanging("MasaGume");
                _MasaGume = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MasaGume");
                OnMasaGumeChanged();
            }
        }
        private Nullable<global::System.Int32> _MasaGume;
        partial void OnMasaGumeChanging(Nullable<global::System.Int32> value);
        partial void OnMasaGumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GornjaTolerancija
        {
            get
            {
                return _GornjaTolerancija;
            }
            set
            {
                OnGornjaTolerancijaChanging(value);
                ReportPropertyChanging("GornjaTolerancija");
                _GornjaTolerancija = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GornjaTolerancija");
                OnGornjaTolerancijaChanged();
            }
        }
        private Nullable<global::System.Int32> _GornjaTolerancija;
        partial void OnGornjaTolerancijaChanging(Nullable<global::System.Int32> value);
        partial void OnGornjaTolerancijaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DonjaTolerancija
        {
            get
            {
                return _DonjaTolerancija;
            }
            set
            {
                OnDonjaTolerancijaChanging(value);
                ReportPropertyChanging("DonjaTolerancija");
                _DonjaTolerancija = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DonjaTolerancija");
                OnDonjaTolerancijaChanged();
            }
        }
        private Nullable<global::System.Int32> _DonjaTolerancija;
        partial void OnDonjaTolerancijaChanging(Nullable<global::System.Int32> value);
        partial void OnDonjaTolerancijaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BrojBubnja
        {
            get
            {
                return _BrojBubnja;
            }
            set
            {
                OnBrojBubnjaChanging(value);
                ReportPropertyChanging("BrojBubnja");
                _BrojBubnja = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BrojBubnja");
                OnBrojBubnjaChanged();
            }
        }
        private global::System.String _BrojBubnja;
        partial void OnBrojBubnjaChanging(global::System.String value);
        partial void OnBrojBubnjaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> KONRastojanjeSredineZObrucaET
        {
            get
            {
                return _KONRastojanjeSredineZObrucaET;
            }
            set
            {
                OnKONRastojanjeSredineZObrucaETChanging(value);
                ReportPropertyChanging("KONRastojanjeSredineZObrucaET");
                _KONRastojanjeSredineZObrucaET = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KONRastojanjeSredineZObrucaET");
                OnKONRastojanjeSredineZObrucaETChanged();
            }
        }
        private Nullable<global::System.Int32> _KONRastojanjeSredineZObrucaET;
        partial void OnKONRastojanjeSredineZObrucaETChanging(Nullable<global::System.Int32> value);
        partial void OnKONRastojanjeSredineZObrucaETChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> KONSirinaPlocicaNaBubnju
        {
            get
            {
                return _KONSirinaPlocicaNaBubnju;
            }
            set
            {
                OnKONSirinaPlocicaNaBubnjuChanging(value);
                ReportPropertyChanging("KONSirinaPlocicaNaBubnju");
                _KONSirinaPlocicaNaBubnju = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KONSirinaPlocicaNaBubnju");
                OnKONSirinaPlocicaNaBubnjuChanged();
            }
        }
        private Nullable<global::System.Int32> _KONSirinaPlocicaNaBubnju;
        partial void OnKONSirinaPlocicaNaBubnjuChanging(Nullable<global::System.Int32> value);
        partial void OnKONSirinaPlocicaNaBubnjuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KONSifraProfila
        {
            get
            {
                return _KONSifraProfila;
            }
            set
            {
                OnKONSifraProfilaChanging(value);
                ReportPropertyChanging("KONSifraProfila");
                _KONSifraProfila = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KONSifraProfila");
                OnKONSifraProfilaChanged();
            }
        }
        private global::System.String _KONSifraProfila;
        partial void OnKONSifraProfilaChanging(global::System.String value);
        partial void OnKONSifraProfilaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> KONBrojPlatna
        {
            get
            {
                return _KONBrojPlatna;
            }
            set
            {
                OnKONBrojPlatnaChanging(value);
                ReportPropertyChanging("KONBrojPlatna");
                _KONBrojPlatna = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KONBrojPlatna");
                OnKONBrojPlatnaChanged();
            }
        }
        private Nullable<global::System.Int32> _KONBrojPlatna;
        partial void OnKONBrojPlatnaChanging(Nullable<global::System.Int32> value);
        partial void OnKONBrojPlatnaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GI
        {
            get
            {
                return _GI;
            }
            set
            {
                OnGIChanging(value);
                ReportPropertyChanging("GI");
                _GI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GI");
                OnGIChanged();
            }
        }
        private Nullable<global::System.Int32> _GI;
        partial void OnGIChanging(Nullable<global::System.Int32> value);
        partial void OnGIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GIDuzina
        {
            get
            {
                return _GIDuzina;
            }
            set
            {
                OnGIDuzinaChanging(value);
                ReportPropertyChanging("GIDuzina");
                _GIDuzina = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GIDuzina");
                OnGIDuzinaChanged();
            }
        }
        private Nullable<global::System.Int32> _GIDuzina;
        partial void OnGIDuzinaChanging(Nullable<global::System.Int32> value);
        partial void OnGIDuzinaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GISifra
        {
            get
            {
                return _GISifra;
            }
            set
            {
                OnGISifraChanging(value);
                ReportPropertyChanging("GISifra");
                _GISifra = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GISifra");
                OnGISifraChanged();
            }
        }
        private global::System.String _GISifra;
        partial void OnGISifraChanging(global::System.String value);
        partial void OnGISifraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GITezina
        {
            get
            {
                return _GITezina;
            }
            set
            {
                OnGITezinaChanging(value);
                ReportPropertyChanging("GITezina");
                _GITezina = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GITezina");
                OnGITezinaChanged();
            }
        }
        private Nullable<global::System.Int32> _GITezina;
        partial void OnGITezinaChanging(Nullable<global::System.Int32> value);
        partial void OnGITezinaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NC1
        {
            get
            {
                return _NC1;
            }
            set
            {
                OnNC1Changing(value);
                ReportPropertyChanging("NC1");
                _NC1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NC1");
                OnNC1Changed();
            }
        }
        private Nullable<global::System.Int32> _NC1;
        partial void OnNC1Changing(Nullable<global::System.Int32> value);
        partial void OnNC1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NC1Duzina
        {
            get
            {
                return _NC1Duzina;
            }
            set
            {
                OnNC1DuzinaChanging(value);
                ReportPropertyChanging("NC1Duzina");
                _NC1Duzina = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NC1Duzina");
                OnNC1DuzinaChanged();
            }
        }
        private Nullable<global::System.Int32> _NC1Duzina;
        partial void OnNC1DuzinaChanging(Nullable<global::System.Int32> value);
        partial void OnNC1DuzinaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NC1Sifra
        {
            get
            {
                return _NC1Sifra;
            }
            set
            {
                OnNC1SifraChanging(value);
                ReportPropertyChanging("NC1Sifra");
                _NC1Sifra = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NC1Sifra");
                OnNC1SifraChanged();
            }
        }
        private global::System.String _NC1Sifra;
        partial void OnNC1SifraChanging(global::System.String value);
        partial void OnNC1SifraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NC1Tezina
        {
            get
            {
                return _NC1Tezina;
            }
            set
            {
                OnNC1TezinaChanging(value);
                ReportPropertyChanging("NC1Tezina");
                _NC1Tezina = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NC1Tezina");
                OnNC1TezinaChanged();
            }
        }
        private Nullable<global::System.Int32> _NC1Tezina;
        partial void OnNC1TezinaChanging(Nullable<global::System.Int32> value);
        partial void OnNC1TezinaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NC2
        {
            get
            {
                return _NC2;
            }
            set
            {
                OnNC2Changing(value);
                ReportPropertyChanging("NC2");
                _NC2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NC2");
                OnNC2Changed();
            }
        }
        private Nullable<global::System.Int32> _NC2;
        partial void OnNC2Changing(Nullable<global::System.Int32> value);
        partial void OnNC2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NC2Duzina
        {
            get
            {
                return _NC2Duzina;
            }
            set
            {
                OnNC2DuzinaChanging(value);
                ReportPropertyChanging("NC2Duzina");
                _NC2Duzina = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NC2Duzina");
                OnNC2DuzinaChanged();
            }
        }
        private Nullable<global::System.Int32> _NC2Duzina;
        partial void OnNC2DuzinaChanging(Nullable<global::System.Int32> value);
        partial void OnNC2DuzinaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NC2Sifra
        {
            get
            {
                return _NC2Sifra;
            }
            set
            {
                OnNC2SifraChanging(value);
                ReportPropertyChanging("NC2Sifra");
                _NC2Sifra = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NC2Sifra");
                OnNC2SifraChanged();
            }
        }
        private global::System.String _NC2Sifra;
        partial void OnNC2SifraChanging(global::System.String value);
        partial void OnNC2SifraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NC2Tezina
        {
            get
            {
                return _NC2Tezina;
            }
            set
            {
                OnNC2TezinaChanging(value);
                ReportPropertyChanging("NC2Tezina");
                _NC2Tezina = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NC2Tezina");
                OnNC2TezinaChanged();
            }
        }
        private Nullable<global::System.Int32> _NC2Tezina;
        partial void OnNC2TezinaChanging(Nullable<global::System.Int32> value);
        partial void OnNC2TezinaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NST1
        {
            get
            {
                return _NST1;
            }
            set
            {
                OnNST1Changing(value);
                ReportPropertyChanging("NST1");
                _NST1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NST1");
                OnNST1Changed();
            }
        }
        private Nullable<global::System.Int32> _NST1;
        partial void OnNST1Changing(Nullable<global::System.Int32> value);
        partial void OnNST1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NST1Duzina
        {
            get
            {
                return _NST1Duzina;
            }
            set
            {
                OnNST1DuzinaChanging(value);
                ReportPropertyChanging("NST1Duzina");
                _NST1Duzina = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NST1Duzina");
                OnNST1DuzinaChanged();
            }
        }
        private Nullable<global::System.Int32> _NST1Duzina;
        partial void OnNST1DuzinaChanging(Nullable<global::System.Int32> value);
        partial void OnNST1DuzinaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NST1Sifra
        {
            get
            {
                return _NST1Sifra;
            }
            set
            {
                OnNST1SifraChanging(value);
                ReportPropertyChanging("NST1Sifra");
                _NST1Sifra = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NST1Sifra");
                OnNST1SifraChanged();
            }
        }
        private global::System.String _NST1Sifra;
        partial void OnNST1SifraChanging(global::System.String value);
        partial void OnNST1SifraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NST1Tezina
        {
            get
            {
                return _NST1Tezina;
            }
            set
            {
                OnNST1TezinaChanging(value);
                ReportPropertyChanging("NST1Tezina");
                _NST1Tezina = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NST1Tezina");
                OnNST1TezinaChanged();
            }
        }
        private Nullable<global::System.Int32> _NST1Tezina;
        partial void OnNST1TezinaChanging(Nullable<global::System.Int32> value);
        partial void OnNST1TezinaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NST2
        {
            get
            {
                return _NST2;
            }
            set
            {
                OnNST2Changing(value);
                ReportPropertyChanging("NST2");
                _NST2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NST2");
                OnNST2Changed();
            }
        }
        private Nullable<global::System.Int32> _NST2;
        partial void OnNST2Changing(Nullable<global::System.Int32> value);
        partial void OnNST2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NST2Duzina
        {
            get
            {
                return _NST2Duzina;
            }
            set
            {
                OnNST2DuzinaChanging(value);
                ReportPropertyChanging("NST2Duzina");
                _NST2Duzina = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NST2Duzina");
                OnNST2DuzinaChanged();
            }
        }
        private Nullable<global::System.Int32> _NST2Duzina;
        partial void OnNST2DuzinaChanging(Nullable<global::System.Int32> value);
        partial void OnNST2DuzinaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NST2Sifra
        {
            get
            {
                return _NST2Sifra;
            }
            set
            {
                OnNST2SifraChanging(value);
                ReportPropertyChanging("NST2Sifra");
                _NST2Sifra = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NST2Sifra");
                OnNST2SifraChanged();
            }
        }
        private global::System.String _NST2Sifra;
        partial void OnNST2SifraChanging(global::System.String value);
        partial void OnNST2SifraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NST2Tezina
        {
            get
            {
                return _NST2Tezina;
            }
            set
            {
                OnNST2TezinaChanging(value);
                ReportPropertyChanging("NST2Tezina");
                _NST2Tezina = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NST2Tezina");
                OnNST2TezinaChanged();
            }
        }
        private Nullable<global::System.Int32> _NST2Tezina;
        partial void OnNST2TezinaChanging(Nullable<global::System.Int32> value);
        partial void OnNST2TezinaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> ANG
        {
            get
            {
                return _ANG;
            }
            set
            {
                OnANGChanging(value);
                ReportPropertyChanging("ANG");
                _ANG = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ANG");
                OnANGChanged();
            }
        }
        private Nullable<global::System.Single> _ANG;
        partial void OnANGChanging(Nullable<global::System.Single> value);
        partial void OnANGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> ANGNST
        {
            get
            {
                return _ANGNST;
            }
            set
            {
                OnANGNSTChanging(value);
                ReportPropertyChanging("ANGNST");
                _ANGNST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ANGNST");
                OnANGNSTChanged();
            }
        }
        private Nullable<global::System.Single> _ANGNST;
        partial void OnANGNSTChanging(Nullable<global::System.Single> value);
        partial void OnANGNSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BTLARG
        {
            get
            {
                return _BTLARG;
            }
            set
            {
                OnBTLARGChanging(value);
                ReportPropertyChanging("BTLARG");
                _BTLARG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BTLARG");
                OnBTLARGChanged();
            }
        }
        private global::System.String _BTLARG;
        partial void OnBTLARGChanging(global::System.String value);
        partial void OnBTLARGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LankTT
        {
            get
            {
                return _LankTT;
            }
            set
            {
                OnLankTTChanging(value);
                ReportPropertyChanging("LankTT");
                _LankTT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LankTT");
                OnLankTTChanged();
            }
        }
        private global::System.String _LankTT;
        partial void OnLankTTChanging(global::System.String value);
        partial void OnLankTTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LankSifra
        {
            get
            {
                return _LankSifra;
            }
            set
            {
                OnLankSifraChanging(value);
                ReportPropertyChanging("LankSifra");
                _LankSifra = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LankSifra");
                OnLankSifraChanged();
            }
        }
        private global::System.String _LankSifra;
        partial void OnLankSifraChanging(global::System.String value);
        partial void OnLankSifraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LankObim
        {
            get
            {
                return _LankObim;
            }
            set
            {
                OnLankObimChanging(value);
                ReportPropertyChanging("LankObim");
                _LankObim = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LankObim");
                OnLankObimChanged();
            }
        }
        private Nullable<global::System.Int32> _LankObim;
        partial void OnLankObimChanging(Nullable<global::System.Int32> value);
        partial void OnLankObimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SirinaRamena
        {
            get
            {
                return _SirinaRamena;
            }
            set
            {
                OnSirinaRamenaChanging(value);
                ReportPropertyChanging("SirinaRamena");
                _SirinaRamena = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SirinaRamena");
                OnSirinaRamenaChanged();
            }
        }
        private Nullable<global::System.Int32> _SirinaRamena;
        partial void OnSirinaRamenaChanging(Nullable<global::System.Int32> value);
        partial void OnSirinaRamenaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UkupnaSirinaFT
        {
            get
            {
                return _UkupnaSirinaFT;
            }
            set
            {
                OnUkupnaSirinaFTChanging(value);
                ReportPropertyChanging("UkupnaSirinaFT");
                _UkupnaSirinaFT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UkupnaSirinaFT");
                OnUkupnaSirinaFTChanged();
            }
        }
        private Nullable<global::System.Int32> _UkupnaSirinaFT;
        partial void OnUkupnaSirinaFTChanging(Nullable<global::System.Int32> value);
        partial void OnUkupnaSirinaFTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PKX
        {
            get
            {
                return _PKX;
            }
            set
            {
                OnPKXChanging(value);
                ReportPropertyChanging("PKX");
                _PKX = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PKX");
                OnPKXChanged();
            }
        }
        private global::System.String _PKX;
        partial void OnPKXChanging(global::System.String value);
        partial void OnPKXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> POIDSFT
        {
            get
            {
                return _POIDSFT;
            }
            set
            {
                OnPOIDSFTChanging(value);
                ReportPropertyChanging("POIDSFT");
                _POIDSFT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("POIDSFT");
                OnPOIDSFTChanged();
            }
        }
        private Nullable<global::System.Int32> _POIDSFT;
        partial void OnPOIDSFTChanging(Nullable<global::System.Int32> value);
        partial void OnPOIDSFTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DuzinaFT
        {
            get
            {
                return _DuzinaFT;
            }
            set
            {
                OnDuzinaFTChanging(value);
                ReportPropertyChanging("DuzinaFT");
                _DuzinaFT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DuzinaFT");
                OnDuzinaFTChanged();
            }
        }
        private Nullable<global::System.Int32> _DuzinaFT;
        partial void OnDuzinaFTChanging(Nullable<global::System.Int32> value);
        partial void OnDuzinaFTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FTET
        {
            get
            {
                return _FTET;
            }
            set
            {
                OnFTETChanging(value);
                ReportPropertyChanging("FTET");
                _FTET = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FTET");
                OnFTETChanged();
            }
        }
        private Nullable<global::System.Int32> _FTET;
        partial void OnFTETChanging(Nullable<global::System.Int32> value);
        partial void OnFTETChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Arhivirana
        {
            get
            {
                return _Arhivirana;
            }
            set
            {
                OnArhiviranaChanging(value);
                ReportPropertyChanging("Arhivirana");
                _Arhivirana = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Arhivirana");
                OnArhiviranaChanged();
            }
        }
        private Nullable<global::System.Boolean> _Arhivirana;
        partial void OnArhiviranaChanging(Nullable<global::System.Boolean> value);
        partial void OnArhiviranaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SpecModel", "FK_Spec_CAI", "CAI")]
        public CAI CAI1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CAI>("SpecModel.FK_Spec_CAI", "CAI").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CAI>("SpecModel.FK_Spec_CAI", "CAI").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CAI> CAI1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CAI>("SpecModel.FK_Spec_CAI", "CAI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CAI>("SpecModel.FK_Spec_CAI", "CAI", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
